http.sslcainfo=C:/Program Files/Git/mingw64/ssl/certs/ca-bundle.crt
http.sslbackend=openssl
diff.astextplain.textconv=astextplain
filter.lfs.clean=git-lfs clean -- %f
filter.lfs.smudge=git-lfs smudge -- %f
filter.lfs.process=git-lfs filter-process
filter.lfs.required=true
credential.helper=manager-core
core.editor=nano.exe
core.autocrlf=true
core.fscache=true
core.symlinks=false
pull.rebase=false
credential.https://dev.azure.com.usehttppath=true
init.defaultbranch=master
user.name=James
user.email=jtfarmer@usc.edu
winupdater.recentlyseenversion=2.19.1.windows.1
filter.lfs.process=git-lfs filter-process
filter.lfs.required=true
filter.lfs.clean=git-lfs clean -- %f
filter.lfs.smudge=git-lfs smudge -- %f
http.sslverify=false
difftool.sourcetree.cmd='' "$LOCAL" "$REMOTE"
mergetool.sourcetree.cmd='' 
mergetool.sourcetree.trustexitcode=true
core.repositoryformatversion=0
core.filemode=false
core.bare=false
core.logallrefupdates=true
core.symlinks=false
core.ignorecase=true
remote.bitbucket.url=https://Levenson-FalkLab@bitbucket.org/Levenson-FalkLab/non-markovian-noise.git
remote.bitbucket.fetch=+refs/heads/*:refs/remotes/bitbucket/*
branch.main.remote=bitbucket
branch.main.merge=refs/heads/main
branch.master.remote=bitbucket
branch.master.merge=refs/heads/master
remote.origin.url=https://github.com/LFL-Lab/Zhinst-measurement
remote.origin.fetch=+refs/heads/*:refs/remotes/origin/*
